---

name: CI/CD
on:
    push:
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
          matrix:
            image: 
                - amazonlinux:2023
        container:
            image: ${{ matrix.image }}
        steps:
            - run: |
                dnf update -y && \
                dnf install -y libicu-devel make cmake3 automake libtool gcc gcc-c++ wget tar \
                    gzip zip libcurl-devel zlib-static libpng-static xz git python python-devel \
                    bzip2-devel which gd-devel
